id: push_to_git
namespace: company.engineering

variables:
  gh_username: koomited
  gh_repo: https://github.com/koomited/dev-to-prod

tasks:
  - id: push_flow
    type: io.kestra.plugin.git.PushFlows
    sourceNamespace: system
    targetNamespace: company.engineering
    flows: "*"
    includeChildNamespaces: true
    gitDirectory: flows
    url: "{{vars.gh_repo}}"
    username: "{{vars.gh_username}}"
    password: "{{secret('GITHUB_ACCESS_TOKEN')}}"
    branch: dev
    commitMessage: "Add flows {{now()}}"


  - id: push_namespace_files
    type: io.kestra.plugin.git.PushNamespaceFiles
    namespace: company.engineering
    files: "*"
    gitDirectory: _files
    url: "{{vars.gh_repo}}"
    username: "{{vars.gh_username}}"
    password: "{{secret('GITHUB_ACCESS_TOKEN')}}"
    branch: dev
    commitMessage: "Add namespace files {{now()}}"

  - id: create_pr
    type: io.kestra.plugin.github.pulls.Create
    oauthToken: "{{secret('GITHUB_ACCESS_TOKEN')}}"
    repository: koomited/dev-to-prod
    sourceBranch: dev
    targetBranch: main
    title: "Merge develop to main"
    body: "Request to merge changes from develop to main"

triggers:
  - id: schedule_push
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 17 * * *"
    disabled: true
